### ISSUE TITLE
python archiver dependencies

### ISSUE THREAD

**Issue by wassfila** [opensmartmesh/osmesh-server#3]
I hit the error No module named pandas, that's definitely easy to solve somehow, but the bigger question is which python dependencies do we need, is there any ideal distribution to install and preferrably for the raspberry pi 3 target platform

**Comment by wassfila** [comment]
a nice wiki's here
http://geoffboeing.com/2016/03/scientific-python-raspberry-pi/

if it's validated, I can update the doc, otherwise just the dependencies we really need.

**Comment by wassfila** [comment]
I installed the pandas dependency, it goes further now, but stil hits a db error. Probably another dependency missing or a database to be configured not sure:

```
`pi@ioserv:~/osmesh-logger/archiver $ python main.py /dev/ttyUSB0
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    A.run()
  File "/home/pi/osmesh-logger/archiver/Server.py", line 57, in run
    conn = DatabaseConnector.connectSQLiteDB('meshDB.db')
TypeError: unbound method connectSQLiteDB() must be called with DatabaseConnector instance as first argument (got str instance instead)`
```

**Comment by redotics** [comment]
Hmm ok I should look into this. 

I would recommend http://conda.pydata.org/miniconda.html because we can also have a dedicated python environment with django. I'll check what I have on my Rpi3
